mod day01;
mod day02;
mod day03;
mod day04;
mod day05;
mod day06;
mod day07;
mod day08;
mod day09;
// mod day10;
// mod day11;
// mod day12;
// mod day13;
// mod day14;
// mod day15;
// mod day16;
// mod day17;
// mod day18;
// mod day19;
// mod day20;
// mod day21;
// mod day22;
// mod day23;
// mod day24;
// mod day25;

fn main() {
    println!("Advent of Code 2023");
    day01::solve_part_one();
    day01::solve_part_two();
    day02::solve_part_one();
    day02::solve_part_two();
    day03::solve_part_one();
    day03::solve_part_two();
    day04::solve_part_one();
    day04::solve_part_two();
    day05::solve_part_one();
    // day05::solve_part_two();
    day06::solve_part_one();
    day06::solve_part_two();
    day07::solve_part_one();
    day07::solve_part_two();
    day08::solve_part_one();
    day08::solve_part_two();
    day09::solve_part_one();
    day09::solve_part_two();
    // day10::solve_part_one();
    // day10::solve_part_two();
    // day11::solve_part_one();
    // day11::solve_part_two();
    // day12::solve_part_one();
    // day12::solve_part_two();
    // day13::solve_part_one();
    // day13::solve_part_two();
    // day14::solve_part_one();
    // day14::solve_part_two();
    // day15::solve_part_one();
    // day15::solve_part_two();
    // day16::solve_part_one();
    // day16::solve_part_two();
    // day17::solve_part_one();
    // day17::solve_part_two();
    // day18::solve_part_one();
    // day18::solve_part_two();
    // day19::solve_part_one();
    // day19::solve_part_two();
    // day20::solve_part_one();
    // day20::solve_part_two();
    // day21::solve_part_one();
    // day21::solve_part_two();
    // day22::solve_part_one();
    // day22::solve_part_one();
    // day23::solve_part_one();
    // day23::solve_part_one();
    // day24::solve_part_two();
    // day24::solve_part_two();
    // day25::solve_part_two();
    // day25::solve_part_two();
}
